module.exports = {
  content: ["./client/index.html", "./client/src/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "light-themebase-colorswhite": "var(--light-themebase-colorswhite)",
        "light-themetext-colorst2": "var(--light-themetext-colorst2)",
        "m-3syslighterror": "var(--m-3syslighterror)",
        "m-3syslightprimary": "var(--m-3syslightprimary)",
        "m-3syslightsurface": "var(--m-3syslightsurface)",
        "m-3white": "var(--m-3white)",
        "m3syslighton-primary": "var(--m3syslighton-primary)",
        "m3syslighton-surface": "var(--m3syslighton-surface)",
        "m3syslighton-surface-variant": "var(--m3syslighton-surface-variant)",
        "m3syslightoutline-variant": "var(--m3syslightoutline-variant)",
        "solid-coloraccenta1": "var(--solid-coloraccenta1)",
        "solid-coloraccenta2": "var(--solid-coloraccenta2)",
        "solid-coloraccenta3": "var(--solid-coloraccenta3)",
        "solid-coloractiondark-orange": "var(--solid-coloractiondark-orange)",
        "solid-coloractiondarkyellow": "var(--solid-coloractiondarkyellow)",
        "solid-coloractionerror-light": "var(--solid-coloractionerror-light)",
        "solid-coloractionlight-orange": "var(--solid-coloractionlight-orange)",
        "solid-coloractionlightyellow": "var(--solid-coloractionlightyellow)",
        "solid-coloractionsuccess-dark": "var(--solid-coloractionsuccess-dark)",
        "solid-coloractionsuccess-light":
          "var(--solid-coloractionsuccess-light)",
        "solid-coloractionwarning-dark": "var(--solid-coloractionwarning-dark)",
        "solid-coloractionwarning-light":
          "var(--solid-coloractionwarning-light)",
        "solid-colorbglight": "var(--solid-colorbglight)",
        "solid-colorbglight-2": "var(--solid-colorbglight-2)",
        "solid-colorlight-bg": "var(--solid-colorlight-bg)",
        "solid-colorlight-bg-2": "var(--solid-colorlight-bg-2)",
        "solid-colorprimary": "var(--solid-colorprimary)",
        "solid-colorsecondary": "var(--solid-colorsecondary)",
        "text-colordark": "var(--text-colordark)",
        "text-colordark-bg": "var(--text-colordark-bg)",
        "text-colorlight": "var(--text-colorlight)",
        "text-colorvery-dark": "var(--text-colorvery-dark)",
        "text-colorvery-light": "var(--text-colorvery-light)",
        "text-colorwhite": "var(--text-colorwhite)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "heading-h1-bold": "var(--heading-h1-bold-font-family)",
        "heading-h1-medium": "var(--heading-h1-medium-font-family)",
        "heading-h2-bold": "var(--heading-h2-bold-font-family)",
        "heading-h2-medium": "var(--heading-h2-medium-font-family)",
        "heading-h3-bold": "var(--heading-h3-bold-font-family)",
        "heading-h3-medium": "var(--heading-h3-medium-font-family)",
        "heading-h4-bold": "var(--heading-h4-bold-font-family)",
        "heading-h4-medium": "var(--heading-h4-medium-font-family)",
        "label-label-1-medium": "var(--label-label-1-medium-font-family)",
        "label-label-1-regular": "var(--label-label-1-regular-font-family)",
        "label-label-1-semi-bold": "var(--label-label-1-semi-bold-font-family)",
        "label-label-2-bold": "var(--label-label-2-bold-font-family)",
        "label-label-2-medium": "var(--label-label-2-medium-font-family)",
        "label-label-2-regular": "var(--label-label-2-regular-font-family)",
        "label-label-2-semi-bold": "var(--label-label-2-semi-bold-font-family)",
        "label-label-3-medium": "var(--label-label-3-medium-font-family)",
        "label-label-3-regular": "var(--label-label-3-regular-font-family)",
        "label-label-3-semi-bold": "var(--label-label-3-semi-bold-font-family)",
        "label-label-4-medium": "var(--label-label-4-medium-font-family)",
        "label-label-5-medium": "var(--label-label-5-medium-font-family)",
        "m3-body-large": "var(--m3-body-large-font-family)",
        "m3-label-large": "var(--m3-label-large-font-family)",
        "m3-title-medium": "var(--m3-title-medium-font-family)",
        "m3-title-small": "var(--m3-title-small-font-family)",
        "tiny-medium": "var(--tiny-medium-font-family)",
        "title-title-2-bold": "var(--title-title-2-bold-font-family)",
        "title-title-3-bold": "var(--title-title-3-bold-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: {
        "drop-shadow-200": "var(--drop-shadow-200)",
        "m3-elevation-light-4": "var(--m3-elevation-light-4)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
  darkMode: ["class"],
};
